version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.7"

submodules:
  include:
    - CoFEA
  recursive: true

python:
   install:
   - requirements: ./requirements.txt

sphinx:
  configuration: ./conf.py
  builder: html
  fail_on_warning: false
